### ISSUE TITLE
Where to buy

### ISSUE THREAD

**Issue by Ronda-00** [alicjamusial/LNA#1]
hello ... I am Ronda ,
Thanking you for your publication,
I congratulate you on your masterful
work and congratulate you on the.
I would ask you to please tell me
where to buy the coils and the
FB1 600R/0.5A component. 
Thank you so much.

**Comment by alicjamusial** [comment]
@Ronda-00 Thanks. Every used component is a standard one and shall be available on TME or any other web store with this kind of stuff.
